/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.User;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vishmi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        lblHomeUserNameRes.setText(User.userName);
        lblHomeRoleRes.setText(User.role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        lblHomeLogo = new javax.swing.JLabel();
        lblHomeUserName = new javax.swing.JLabel();
        lblHomeRole = new javax.swing.JLabel();
        lblHomeRoleRes = new javax.swing.JLabel();
        lblHomeUserNameRes = new javax.swing.JLabel();
        menuMinClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        btnMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();
        lblTopLogo = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        lblHomePanel = new javax.swing.JLabel();
        productPanel = new javax.swing.JPanel();
        lblProductPanel = new javax.swing.JLabel();
        returnsPanel = new javax.swing.JPanel();
        lblReturnsPanel = new javax.swing.JLabel();
        issuesPanel = new javax.swing.JPanel();
        lblIssuesPanel = new javax.swing.JLabel();
        stockPanel = new javax.swing.JPanel();
        lblStockPanel = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        lblUserPanel = new javax.swing.JLabel();
        logOutPanel = new javax.swing.JPanel();
        lblLogOutPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(186, 238, 180));

        sidePanel.setBackground(new java.awt.Color(8, 102, 1));

        lblHomeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeLogo.png"))); // NOI18N

        lblHomeUserName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblHomeUserName.setText("User Name: ");

        lblHomeRole.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblHomeRole.setText("Role :");

        lblHomeRoleRes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N

        lblHomeUserNameRes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblHomeLogo)
                .addGap(77, 77, 77)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHomeRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomeUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHomeRoleRes, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeUserNameRes, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHomeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHomeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHomeUserNameRes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHomeRoleRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHomeRole, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        menuMinClose.setBackground(new java.awt.Color(186, 238, 180));
        menuMinClose.setPreferredSize(new java.awt.Dimension(80, 40));

        btnClose.setBackground(new java.awt.Color(186, 238, 180));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close_icon.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose)
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose)
        );

        btnMin.setBackground(new java.awt.Color(186, 238, 180));

        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize_icon.png"))); // NOI18N
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMinLayout = new javax.swing.GroupLayout(btnMin);
        btnMin.setLayout(btnMinLayout);
        btnMinLayout.setHorizontalGroup(
            btnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin)
        );
        btnMinLayout.setVerticalGroup(
            btnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin)
        );

        javax.swing.GroupLayout menuMinCloseLayout = new javax.swing.GroupLayout(menuMinClose);
        menuMinClose.setLayout(menuMinCloseLayout);
        menuMinCloseLayout.setHorizontalGroup(
            menuMinCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMinCloseLayout.createSequentialGroup()
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuMinCloseLayout.setVerticalGroup(
            menuMinCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblTopLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/TopLogo.png"))); // NOI18N

        homePanel.setBackground(new java.awt.Color(186, 238, 180));
        homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblHomePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeMenuIcon.png"))); // NOI18N
        lblHomePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomePanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        productPanel.setBackground(new java.awt.Color(186, 238, 180));
        productPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblProductPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/productMenuIcon.png"))); // NOI18N
        lblProductPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProductPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        returnsPanel.setBackground(new java.awt.Color(186, 238, 180));
        returnsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblReturnsPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturnsPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/returnsMenuIcon.png"))); // NOI18N
        lblReturnsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReturnsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReturnsPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout returnsPanelLayout = new javax.swing.GroupLayout(returnsPanel);
        returnsPanel.setLayout(returnsPanelLayout);
        returnsPanelLayout.setHorizontalGroup(
            returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReturnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        returnsPanelLayout.setVerticalGroup(
            returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReturnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        issuesPanel.setBackground(new java.awt.Color(186, 238, 180));
        issuesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblIssuesPanel.setBackground(new java.awt.Color(186, 238, 180));
        lblIssuesPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIssuesPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/issuesMenuIcon.png"))); // NOI18N
        lblIssuesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIssuesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIssuesPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout issuesPanelLayout = new javax.swing.GroupLayout(issuesPanel);
        issuesPanel.setLayout(issuesPanelLayout);
        issuesPanelLayout.setHorizontalGroup(
            issuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIssuesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        issuesPanelLayout.setVerticalGroup(
            issuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIssuesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        stockPanel.setBackground(new java.awt.Color(186, 238, 180));
        stockPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblStockPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stockMenuIcon.png"))); // NOI18N
        lblStockPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStockPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStockPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        userPanel.setBackground(new java.awt.Color(186, 238, 180));
        userPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUserPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userMenuIcon.png"))); // NOI18N
        lblUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logOutPanel.setBackground(new java.awt.Color(186, 238, 180));

        lblLogOutPanel.setBackground(new java.awt.Color(186, 238, 180));
        lblLogOutPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOutPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        lblLogOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logOutPanelLayout = new javax.swing.GroupLayout(logOutPanel);
        logOutPanel.setLayout(logOutPanelLayout);
        logOutPanelLayout.setHorizontalGroup(
            logOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
        );
        logOutPanelLayout.setVerticalGroup(
            logOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lblTopLogo)
                        .addGap(930, 930, 930)
                        .addComponent(menuMinClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(stockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(issuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(returnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(860, 860, 860)
                        .addComponent(logOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTopLogo)
                    .addComponent(menuMinClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(logOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        changecolor(btnMin,new Color(186,238,180));
    }//GEN-LAST:event_lblMinMouseExited

    private void lblMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseEntered
        changecolor(btnMin,new Color(207, 211, 207));
    }//GEN-LAST:event_lblMinMouseEntered

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        try {
            this.setState(ICONIFIED);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        changecolor(btnClose,new Color(186,238,180));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        changecolor(btnClose,new Color(207, 211, 207));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblHomePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePanelMouseEntered
        changecolor(homePanel,new Color(8,102,1));
    }//GEN-LAST:event_lblHomePanelMouseEntered

    private void lblHomePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomePanelMouseExited
        changecolor(homePanel,new Color(186,238,180));
    }//GEN-LAST:event_lblHomePanelMouseExited

    private void lblUserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserPanelMouseExited
        changecolor(userPanel,new Color(186,238,180));
    }//GEN-LAST:event_lblUserPanelMouseExited

    private void lblUserPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserPanelMouseEntered
        changecolor(userPanel,new Color(8,102,1));
    }//GEN-LAST:event_lblUserPanelMouseEntered

    private void lblProductPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductPanelMouseEntered
        changecolor(productPanel,new Color(8,102,1));
    }//GEN-LAST:event_lblProductPanelMouseEntered

    private void lblProductPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductPanelMouseExited
        changecolor(productPanel,new Color(186,238,180));
    }//GEN-LAST:event_lblProductPanelMouseExited

    private void lblStockPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockPanelMouseEntered
        changecolor(stockPanel,new Color(8,102,1));
    }//GEN-LAST:event_lblStockPanelMouseEntered

    private void lblStockPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStockPanelMouseExited
        changecolor(stockPanel,new Color(186,238,180));
    }//GEN-LAST:event_lblStockPanelMouseExited

    private void lblIssuesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIssuesPanelMouseEntered
        changecolor(issuesPanel,new Color(8,102,1));
    }//GEN-LAST:event_lblIssuesPanelMouseEntered

    private void lblIssuesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIssuesPanelMouseExited
        changecolor(issuesPanel,new Color(186,238,180));
    }//GEN-LAST:event_lblIssuesPanelMouseExited

    private void lblReturnsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnsPanelMouseEntered
         changecolor(returnsPanel,new Color(8,102,1));
    }//GEN-LAST:event_lblReturnsPanelMouseEntered

    private void lblReturnsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnsPanelMouseExited
        changecolor(returnsPanel,new Color(186,238,180));
    }//GEN-LAST:event_lblReturnsPanelMouseExited

    private void lblLogOutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutPanelMouseEntered
        changecolor(logOutPanel,new Color(8,102,1));
    }//GEN-LAST:event_lblLogOutPanelMouseEntered

    private void lblLogOutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutPanelMouseExited
        changecolor(logOutPanel,new Color(186,238,180));
    }//GEN-LAST:event_lblLogOutPanelMouseExited

    private void lblLogOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutPanelMouseClicked
        //logout button 
        int pop = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", pop);
        if (result == 0) {
            Login frame = new Login();
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblLogOutPanelMouseClicked

    private void lblUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserPanelMouseClicked
       UserManagement frame = new UserManagement();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblUserPanelMouseClicked

    private void lblProductPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductPanelMouseClicked
        
    }//GEN-LAST:event_lblProductPanelMouseClicked

   public void changecolor(JPanel hover, Color rand ){
       hover.setBackground(rand);
   } 
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnMin;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel issuesPanel;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblHomeLogo;
    private javax.swing.JLabel lblHomePanel;
    private javax.swing.JLabel lblHomeRole;
    private javax.swing.JLabel lblHomeRoleRes;
    private javax.swing.JLabel lblHomeUserName;
    private javax.swing.JLabel lblHomeUserNameRes;
    private javax.swing.JLabel lblIssuesPanel;
    private javax.swing.JLabel lblLogOutPanel;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblProductPanel;
    private javax.swing.JLabel lblReturnsPanel;
    private javax.swing.JLabel lblStockPanel;
    private javax.swing.JLabel lblTopLogo;
    private javax.swing.JLabel lblUserPanel;
    private javax.swing.JPanel logOutPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuMinClose;
    private javax.swing.JPanel productPanel;
    private javax.swing.JPanel returnsPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel stockPanel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
