/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseLayer.DB_connection;
import Models.Operations;
import Models.User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Vishmi
 */
public class Login extends javax.swing.JFrame {
    
    static User currentUser;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Dimension dim =Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        txtLoginEmail.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoginEmail = new javax.swing.JLabel();
        jSeparatorEmail = new javax.swing.JSeparator();
        txtLoginEmail = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        jSeparatorPassword = new javax.swing.JSeparator();
        jPasswordFieldLogin = new javax.swing.JPasswordField();
        jButtonLogIn = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLoginRole = new javax.swing.JLabel();
        lblLoginBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 656));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoginEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        lblLoginEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginEmail.setText("Email :");
        jPanel1.add(lblLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 40));

        jSeparatorEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparatorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 370, 10));

        txtLoginEmail.setBackground(new java.awt.Color(108, 186, 116));
        txtLoginEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        txtLoginEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtLoginEmail.setText("you@example.com");
        txtLoginEmail.setBorder(null);
        txtLoginEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginEmailFocusGained(evt);
            }
        });
        jPanel1.add(txtLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 370, 40));

        lblLoginPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        lblLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginPassword.setText("Password :");
        jPanel1.add(lblLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 140, 40));

        jSeparatorPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparatorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 370, 10));

        jPasswordFieldLogin.setBackground(new java.awt.Color(87, 167, 90));
        jPasswordFieldLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jPasswordFieldLogin.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldLogin.setText("jPasswordField1");
        jPasswordFieldLogin.setBorder(null);
        jPasswordFieldLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldLoginFocusGained(evt);
            }
        });
        jPanel1.add(jPasswordFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 370, 40));

        jButtonLogIn.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogIn.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButtonLogIn.setForeground(new java.awt.Color(8, 102, 1));
        jButtonLogIn.setText("Sign In");
        jButtonLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogInMouseClicked(evt);
            }
        });
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 160, 40));

        jCheckBox3.setBackground(new java.awt.Color(0, 102, 0));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(102, 255, 102));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Store Manager", "Store Keeper", "Sales Rep" }));
        jComboBox1.setBorder(null);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 310, 40));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("<html> <body> <u>Terms And Conditions.</u> </body> </html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 170, 20));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Agree");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 70, 20));

        lblLoginRole.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        lblLoginRole.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginRole.setText("Role :");
        jPanel1.add(lblLoginRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 60, 40));

        lblLoginBg.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLoginBg.setForeground(new java.awt.Color(0, 0, 0));
        lblLoginBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginUi.png"))); // NOI18N
        jPanel1.add(lblLoginBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginEmailFocusGained
        txtLoginEmail.setText("");
    }//GEN-LAST:event_txtLoginEmailFocusGained

    private void jPasswordFieldLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldLoginFocusGained
        jPasswordFieldLogin.setText("");
    }//GEN-LAST:event_jPasswordFieldLoginFocusGained

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButtonLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogInMouseClicked
        Home frame = new Home();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogInMouseClicked

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
        // TODO add your handling code here:
        Operations operations = new Operations();
        
        try {
            String emailStr = txtLoginEmail.getText();
            String passwordStr = jPasswordFieldLogin.getText();
            String roleStr = jComboBox1.getSelectedItem().toString();
            
            if (operations.isLogin(emailStr, passwordStr, roleStr, this)){
                new Home().setVisible(true);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Please Insert Correct Email/Password.");
            }
        }
        catch (Exception exception){
            JOptionPane.showMessageDialog(this,"Please Insert Correct Informations.");
        }
    
    }//GEN-LAST:event_jButtonLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JSeparator jSeparatorEmail;
    private javax.swing.JSeparator jSeparatorPassword;
    private javax.swing.JLabel lblLoginBg;
    private javax.swing.JLabel lblLoginEmail;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginRole;
    private javax.swing.JTextField txtLoginEmail;
    // End of variables declaration//GEN-END:variables
}
