/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseLayer.DB_connection;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Vishmi
 */
public class UserManagementSearch extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    boolean a = true;

    public UserManagementSearch() {
        initComponents();
        loadsup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logOutPanel = new javax.swing.JPanel();
        lblLogOutPanel = new javax.swing.JLabel();
        lblSideBarLogo = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblIssues = new javax.swing.JLabel();
        lblReturn = new javax.swing.JLabel();
        menuMinClose = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        btnMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();
        lblTopPanel = new javax.swing.JPanel();
        lblInsertUserTopBar = new javax.swing.JLabel();
        lblEditUserTopBar = new javax.swing.JLabel();
        lblTopic = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUserSearch = new javax.swing.JTable();
        btnUpdate = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        txtContactNoSearch = new javax.swing.JTextField();
        lblContactNoSearch = new javax.swing.JLabel();
        lblConPasswordSearch = new javax.swing.JLabel();
        txtConPasswordSearch = new javax.swing.JTextField();
        txtPasswordSearch = new javax.swing.JTextField();
        lblPasswordSearch = new javax.swing.JLabel();
        lblNICSearch = new javax.swing.JLabel();
        txtNICSearch = new javax.swing.JTextField();
        txtUserIDSearch = new javax.swing.JTextField();
        lblUserIDSearch = new javax.swing.JLabel();
        lblUserNameSearch = new javax.swing.JLabel();
        txtUserNameSearch = new javax.swing.JTextField();
        txtEmailSearch = new javax.swing.JTextField();
        lblEmailSearch = new javax.swing.JLabel();
        lblRoleSearch = new javax.swing.JLabel();
        txtRoleSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSearch = new javax.swing.JList<>();
        BtnPrintReport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(186, 238, 180));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(8, 102, 1));

        logOutPanel.setBackground(new java.awt.Color(8, 102, 1));

        lblLogOutPanel.setBackground(new java.awt.Color(186, 238, 180));
        lblLogOutPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOutPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        lblLogOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutPanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logOutPanelLayout = new javax.swing.GroupLayout(logOutPanel);
        logOutPanel.setLayout(logOutPanelLayout);
        logOutPanelLayout.setHorizontalGroup(
            logOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
        );
        logOutPanelLayout.setVerticalGroup(
            logOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        lblSideBarLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSideBarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/otherSideBarLogo.png"))); // NOI18N

        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/btnHome.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/btnUser.png"))); // NOI18N

        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/btnProduct.png"))); // NOI18N
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductMouseClicked(evt);
            }
        });

        lblStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/btnStock.png"))); // NOI18N

        lblIssues.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/btnIssues.png"))); // NOI18N

        lblReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/btnReturns.png"))); // NOI18N

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(lblSideBarLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSideBarLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHome)
                .addGap(24, 24, 24)
                .addComponent(lblUser)
                .addGap(24, 24, 24)
                .addComponent(lblProduct)
                .addGap(24, 24, 24)
                .addComponent(lblStock)
                .addGap(24, 24, 24)
                .addComponent(lblIssues)
                .addGap(24, 24, 24)
                .addComponent(lblReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(logOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        menuMinClose.setBackground(new java.awt.Color(186, 238, 180));
        menuMinClose.setPreferredSize(new java.awt.Dimension(80, 40));

        btnClose.setBackground(new java.awt.Color(186, 238, 180));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close_icon.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose)
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClose)
        );

        btnMin.setBackground(new java.awt.Color(186, 238, 180));

        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize_icon.png"))); // NOI18N
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMinLayout = new javax.swing.GroupLayout(btnMin);
        btnMin.setLayout(btnMinLayout);
        btnMinLayout.setHorizontalGroup(
            btnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin)
        );
        btnMinLayout.setVerticalGroup(
            btnMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMin)
        );

        javax.swing.GroupLayout menuMinCloseLayout = new javax.swing.GroupLayout(menuMinClose);
        menuMinClose.setLayout(menuMinCloseLayout);
        menuMinCloseLayout.setHorizontalGroup(
            menuMinCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMinCloseLayout.createSequentialGroup()
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        menuMinCloseLayout.setVerticalGroup(
            menuMinCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainPanel.add(menuMinClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));

        lblTopPanel.setBackground(new java.awt.Color(37, 135, 26));

        lblInsertUserTopBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInsertUserTopBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/insertUserTopBar.png"))); // NOI18N
        lblInsertUserTopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsertUserTopBarMouseClicked(evt);
            }
        });

        lblEditUserTopBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditUserTopBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/editUserTopBar.png"))); // NOI18N

        javax.swing.GroupLayout lblTopPanelLayout = new javax.swing.GroupLayout(lblTopPanel);
        lblTopPanel.setLayout(lblTopPanelLayout);
        lblTopPanelLayout.setHorizontalGroup(
            lblTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInsertUserTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditUserTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        lblTopPanelLayout.setVerticalGroup(
            lblTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEditUserTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInsertUserTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        mainPanel.add(lblTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 820, 60));

        lblTopic.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblTopic.setForeground(new java.awt.Color(0, 0, 0));
        lblTopic.setText("Edit & Delete User Management");
        mainPanel.add(lblTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 460, 40));

        jPanel1.setBackground(new java.awt.Color(186, 238, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTableUserSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTableUserSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableUserSearch.setForeground(new java.awt.Color(0, 0, 0));
        jTableUserSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Name", "Email", "NIC", "Password", "Con. Password", "Contact No", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableUserSearch.setToolTipText("");
        jTableUserSearch.setGridColor(new java.awt.Color(102, 102, 102));
        jTableUserSearch.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTableUserSearch.setSelectionForeground(new java.awt.Color(204, 204, 255));
        jTableUserSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUserSearch);

        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/update.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/delete.png"))); // NOI18N
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        txtContactNoSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtContactNoSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtContactNoSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtContactNoSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblContactNoSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblContactNoSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblContactNoSearch.setText("Contact No :");

        lblConPasswordSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblConPasswordSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblConPasswordSearch.setText("Con. Password :");

        txtConPasswordSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtConPasswordSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtConPasswordSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtConPasswordSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPasswordSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtPasswordSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPasswordSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPasswordSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordSearchActionPerformed(evt);
            }
        });

        lblPasswordSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPasswordSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblPasswordSearch.setText("Password :");

        lblNICSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNICSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblNICSearch.setText("NIC Number :");

        txtNICSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtNICSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNICSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtNICSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtUserIDSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtUserIDSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserIDSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtUserIDSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUserIDSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserIDSearchKeyReleased(evt);
            }
        });

        lblUserIDSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUserIDSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblUserIDSearch.setText("User ID :");

        lblUserNameSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUserNameSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblUserNameSearch.setText("User Name :");

        txtUserNameSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtUserNameSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUserNameSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtUserNameSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtEmailSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtEmailSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmailSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblEmailSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEmailSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblEmailSearch.setText("Email :");

        lblRoleSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRoleSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblRoleSearch.setText("Role :");

        txtRoleSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtRoleSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRoleSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtRoleSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jListSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSearchMouseClicked(evt);
            }
        });
        jListSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jListSearchKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jListSearch);

        BtnPrintReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnPrintReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/btnPrntRep.png"))); // NOI18N
        BtnPrintReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrintReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUserIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtUserIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lblNICSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtNICSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(lblPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(BtnPrintReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtEmailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRoleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtRoleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblUserNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtUserNameSearch))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblConPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txtConPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblContactNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtContactNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNICSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNICSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtConPasswordSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblContactNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtContactNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtUserNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtEmailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtRoleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnPrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        changecolor(btnMin, new Color(186, 238, 180));
    }//GEN-LAST:event_lblMinMouseExited

    private void lblMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseEntered
        changecolor(btnMin, new Color(207, 211, 207));
    }//GEN-LAST:event_lblMinMouseEntered

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        try {
            this.setState(ICONIFIED);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        changecolor(btnClose, new Color(186, 238, 180));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        changecolor(btnClose, new Color(207, 211, 207));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblLogOutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutPanelMouseEntered
        changecolor(logOutPanel, new Color(186, 238, 180));
    }//GEN-LAST:event_lblLogOutPanelMouseEntered

    private void lblLogOutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutPanelMouseExited
        changecolor(logOutPanel, new Color(8, 102, 1));
    }//GEN-LAST:event_lblLogOutPanelMouseExited

    private void lblLogOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutPanelMouseClicked
        //logout button 
        int pop = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", pop);
        if (result == 0) {
            Login frame = new Login();
            frame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblLogOutPanelMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        Home frame = new Home();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseClicked

    }//GEN-LAST:event_lblProductMouseClicked

    private void txtPasswordSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordSearchActionPerformed

    private void lblInsertUserTopBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertUserTopBarMouseClicked
        UserManagement frame = new UserManagement();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblInsertUserTopBarMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        try {
            String userID = txtUserIDSearch.getText();
            String userName = txtUserNameSearch.getText();
            String email = txtEmailSearch.getText();
            String nic = txtNICSearch.getText();
            String password = txtPasswordSearch.getText();
            String con_password = txtConPasswordSearch.getText();
            String role = txtRoleSearch.getText();
            String contactNo = txtContactNoSearch.getText();
            DB_connection.iud("UPDATE user SET userName = '" + userName + "', email = '" + email + "', nicNumber = '" + nic + "', password = '" + password + "', conPassword = '" + con_password + "', contatcNo = '" + contactNo + "', role = '" + role + "'");
            loadsup();
            JOptionPane.showMessageDialog(this, "User Table Updated.");
            clearAll();
        } catch (Exception ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void jTableUserSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserSearchMouseClicked
        // TODO add your handling code here:
        try {
            int i = jTableUserSearch.getSelectedRow();
            txtUserIDSearch.setText((String) jTableUserSearch.getValueAt(i, 0));
            txtUserNameSearch.setText((String) jTableUserSearch.getValueAt(i, 1));
            txtEmailSearch.setText((String) jTableUserSearch.getValueAt(i, 2));
            txtNICSearch.setText((String) jTableUserSearch.getValueAt(i, 3));
            txtPasswordSearch.setText((String) jTableUserSearch.getValueAt(i, 4));
            txtConPasswordSearch.setText((String) jTableUserSearch.getValueAt(i, 5));
            txtContactNoSearch.setText((String) jTableUserSearch.getValueAt(i, 6));
            txtRoleSearch.setText((String) jTableUserSearch.getValueAt(i, 7));
            search();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTableUserSearchMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        try {
            String userID = txtUserIDSearch.getText();

            String id = "";
            ResultSet rs = DB_connection.search("select * from user where userId = '" + userID + "'");

            while (rs.next()) {
                id = rs.getString("idUser");
            }

            DB_connection.iud("DELETE FROM user where userId = '" + userID + "'");

            JOptionPane.showMessageDialog(this, "User deleted.");
            loadsup();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void jListSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListSearchKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtUserIDSearch.setText(jListSearch.getSelectedValue().toString());
            jScrollPane2.setVisible(false);
            search();
            txtUserIDSearch.grabFocus();
        }
    }//GEN-LAST:event_jListSearchKeyReleased

    private void jListSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSearchMouseClicked
        // TODO add your handling code here:
        txtUserIDSearch.setText(jListSearch.getSelectedValue().toString());
        jScrollPane2.setVisible(false);
        search();
        txtUserIDSearch.grabFocus();
    }//GEN-LAST:event_jListSearchMouseClicked

    private void txtUserIDSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIDSearchKeyReleased
        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jListSearch.grabFocus();
                jListSearch.setSelectedIndex(0);
            } else if (txtUserIDSearch.getText().equals("")) {
                jScrollPane2.setVisible(false);
            } else {
                ResultSet rs = DB_connection.search("select * from user where userId like '%" + txtUserIDSearch.getText() + "%'");
                Vector v = new Vector();
                while (rs.next()) {
                    v.add(rs.getString("userId"));
                }
                jListSearch.setListData(v);
                if (v.equals("")) {
                    jScrollPane2.setVisible(false);
                }
                jScrollPane2.setVisible(true);
                jPanel1.updateUI();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtUserIDSearchKeyReleased

    private void BtnPrintReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrintReportMouseClicked
        // TODO add your handling code here:
        try {
            Connection c = DB_connection.getDB();

            JasperDesign jasdi = JRXmlLoader.load("E:\\Sliit lecture slides\\2nd year 2nd sem\\pract\\Agrinova\\src\\Reports\\UserReport.jrxml");
            String sql = "SELECT `idUser`, `userId`, `userName`, `email`, `nicNumber`, `contatcNo`, `password`, `conPassword`, `role` FROM `user`";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jasdi.setQuery(newQuery);
            JasperReport js = JasperCompileManager.compileReport(jasdi);
            JasperPrint jp = JasperFillManager.fillReport(js, null, c);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_BtnPrintReportMouseClicked

    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagementSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagementSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagementSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagementSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagementSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnPrintReport;
    private javax.swing.JPanel btnClose;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JPanel btnMin;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JList<String> jListSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUserSearch;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConPasswordSearch;
    private javax.swing.JLabel lblContactNoSearch;
    private javax.swing.JLabel lblEditUserTopBar;
    private javax.swing.JLabel lblEmailSearch;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblInsertUserTopBar;
    private javax.swing.JLabel lblIssues;
    private javax.swing.JLabel lblLogOutPanel;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblNICSearch;
    private javax.swing.JLabel lblPasswordSearch;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblRoleSearch;
    private javax.swing.JLabel lblSideBarLogo;
    private javax.swing.JLabel lblStock;
    private javax.swing.JPanel lblTopPanel;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserIDSearch;
    private javax.swing.JLabel lblUserNameSearch;
    private javax.swing.JPanel logOutPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuMinClose;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField txtConPasswordSearch;
    private javax.swing.JTextField txtContactNoSearch;
    private javax.swing.JTextField txtEmailSearch;
    private javax.swing.JTextField txtNICSearch;
    private javax.swing.JTextField txtPasswordSearch;
    private javax.swing.JTextField txtRoleSearch;
    private javax.swing.JTextField txtUserIDSearch;
    private javax.swing.JTextField txtUserNameSearch;
    // End of variables declaration//GEN-END:variables

    private void loadsup() {
        try {
            jTableUserSearch.removeAll();
            jTableUserSearch.repaint();
            jTableUserSearch.revalidate();
            DefaultTableModel dtm = (DefaultTableModel) jTableUserSearch.getModel();
            dtm.getDataVector().removeAllElements();
            ResultSet sr = DB_connection.search("select * from user");

            while (sr.next()) {

                Vector v = new Vector();
                v.add(sr.getString("userId"));
                v.add(sr.getString("userName"));
                v.add(sr.getString("email"));
                v.add(sr.getString("nicNumber"));
                v.add(sr.getString("password"));
                v.add(sr.getString("conPassword"));
                v.add(sr.getString("contatcNo"));
                v.add(sr.getString("role"));

                dtm.addRow(v);
            }
            txtUserIDSearch.grabFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void search() {
        try {
            String id = "";
            ResultSet rs = DB_connection.search("select * from user where userId = '" + txtUserIDSearch.getText() + "'");

            while (rs.next()) {
                txtUserNameSearch.setText(rs.getString("userName"));
                txtEmailSearch.setText(rs.getString("email"));
                txtNICSearch.setText(rs.getString("nicNumber"));
                txtPasswordSearch.setText(rs.getString("password"));
                txtConPasswordSearch.setText(rs.getString("conPassword"));
                txtContactNoSearch.setText(rs.getString("contatcNo"));
                txtRoleSearch.setText(rs.getString("role"));
                id = rs.getString("idUser");
            }
            jTableUserSearch.removeAll();
            jTableUserSearch.repaint();
            jTableUserSearch.revalidate();
            DefaultTableModel dtm = (DefaultTableModel) jTableUserSearch.getModel();
            dtm.getDataVector().removeAllElements();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void clearAll() {
        txtUserIDSearch.setText("");
        txtUserNameSearch.setText("");
        txtEmailSearch.setText("");
        txtNICSearch.setText("");
        txtPasswordSearch.setText("");
        txtConPasswordSearch.setText("");
        txtContactNoSearch.setText("");
        txtRoleSearch.setText("");
        jTableUserSearch.removeAll();
        jTableUserSearch.repaint();
        jTableUserSearch.revalidate();
        /*DefaultTableModel dtm = (DefaultTableModel) jTableUserSearch.getModel();
        dtm.setRowCount(0);*/
    }

}
